Milestone5
MarioDena/react-calculator pull request #6
Opened 2020-08-30 21:55 UTC by MarioDena

Implemented handlers and stateless components

2020-08-30 23:30 UTC, shloch requested changes
## Hello @MarioDena 

Great job...really works great, you joint the components together properly and the project works
![calc](https://user-images.githubusercontent.com/40712459/91671733-27a82300-eb21-11ea-93b5-6a9b12f65aae.gif)

I however want you to manage one aspect before you get a thumbs up. I want you to manage division by ZERO. when I want to divide by zero, it's not possible. Make it possible and return `NaN` or `Error`

Make the error none to the user

Thanks

2020-08-30 23:30 UTC, shloch commented on src/logic/Operate.js
> +      break;
handle division by ZERO

2020-08-31 02:39 UTC, MarioDena commented on src/logic/Operate.js
> +      break;
On a side note I did Handle the division by 0, that's why the calculator won't let you do something that is impossible. I did what you asked but it is:
1.- Redundant 
2.- Not in the requirements to handle that division in the way you want. Just to handle the problem.

2020-08-31 02:50 UTC, MarioDena commented on src/logic/Operate.js
> +      break;
I did what you asked but this error was already handled in App.js for reference check the code there the behavior was as intended

2020-08-31 07:59 UTC, bellom requested changes
## Hi @MarioDena  :clap: 

**Great work making `almost` all the necessary corrections from the previous review.**

**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-08-31 07:59 UTC, bellom commented on src/logic/Operate.js
> +      result = first.times(second.div(100));
Awesome work using a ternary operator but what the previous reviewer is saying is; we should have an error message if a user tries to divide a number by `0`.
Something like this; 👇 
![image](https://user-images.githubusercontent.com/31897434/91696912-336b0800-eb68-11ea-9e57-8dd3a5551faf.png)

2020-08-31 10:42 UTC, MarioDena commented on src/logic/Operate.js
> +      result = first.times(second.div(100));
Yes And like I said division by Zero is handled by App.js 
Having an Error message is not specified in the project, thus not mandatory.

2020-08-31 16:47 UTC, whiz25 approved these changes
## Approved :clap: 
You have done well and it's a :+1: from me. Merge and proceed to the next milestone.

### Martin Afani

2020-08-31 19:41 UTC, merged